### ISSUE TITLE
framework link

### ISSUE THREAD

**Issue by MZorzy** [mtconnect/adapter#10]
on first page http://projects.mtconnect.org/projects/show/adapters -> 404

there are some HOWTO from .dll to adapter ?

**Comment by wsobel** [comment]
I am not sure what you are referring to. There is no adapters project anymore. 

Please give me some more details regarding your issues?

**Comment by MZorzy** [comment]
this Repo, this page https://github.com/mtconnect/adapter there is a non exixistent link.

no project anymoRe ?  i have mitsubishi .dll and API and want to do an adapter,
as fanuc do with focas dll.

**Comment by wsobel** [comment]
There is no project anymore. The projects website is only for development of the standard.

**Comment by wsobel** [comment]
Got it! Thanks for pointing that out. I have removed the link.
