### ISSUE TITLE
Fanuc adapter (result = -16)

### ISSUE THREAD

**Issue by sankarshvittal** [mtconnect/adapter#11]
I have been attempting to set this adapter . I have followed the example on

http://www.ellisware.com/wordpress/mtconnect-adapter-for-windows/

My results above are from the adapter:

![image](https://user-images.githubusercontent.com/31777036/40852914-1e116c98-659a-11e8-93ba-c63920a469e4.png)

Does anyone have any ideas the reason for this issue?

**Comment by wsobel** [comment]
This is a FANUC error that the library could not connect to the machine. Check to make sure you have the correct IP address and the machine is turned on and that port 8193 can be connected to from a TCP connection (telnet).

Best,
W

**Comment by sankarshvittal** [comment]
Thank you for pointing that out. It is working fine now.

**Comment by Stayme7o** [comment]
> I have been attempting to set this adapter . I have followed the example on
> 
> http://www.ellisware.com/wordpress/mtconnect-adapter-for-windows/
> 
> My results above are from the adapter:
> 
> ![image](https://user-images.githubusercontent.com/31777036/40852914-1e116c98-659a-11e8-93ba-c63920a469e4.png)
> 
> Does anyone have any ideas the reason for this issue?

hello,i'm trying to make an adapter for my FANUC to transform the data to fit MTConnect,and your website is shown on sale:http://www.ellisware.com/wordpress/mtconnect-adapter-for-windows/
