### ISSUE TITLE
MT connect error with fanuc Result: -15 error

### ISSUE THREAD

**Issue by memayank2007** [mtconnect/adapter#14]
Hello ,

I am trying to get data from fanuc 0id using this mtconnect agent .Build getting successful but after that data is not being display on browser as well as cmd .

![img-20181016-wa0001](https://user-images.githubusercontent.com/5354069/47023226-d08f4400-d17c-11e8-940d-3483e297b803.jpg)

Connecting to machine at 192.168.1.1 and port 8193
 Result: -15.

When i ping cnc ip from cmd and vice versa its working fine not getting any error .

Whats wrong here . what could be issue ?

**Comment by wsobel** [comment]
The adapter just connects to the machine, it is not the mtconnect agent and does not have an HTTP server embedded. You should use the cppagent in the mtconnect GitHub repo. 

The connection result of -15 means it cannot connect to the machine tool controller. Make sure there is something bound to port 8193. You can test this with telnet.

Best 
Will

**Comment by memayank2007** [comment]
Hello Will,

Got you point . I have installed C++ MTConnect CPPagent on my windows machine and can see the dummy data on localhost:5000/current .

I tried to telnet to machine IP on port 8193 which is opening new window which i suppose is successful .but still i am **getting the same result -15** . Every time i tried to connect with FANUC 0id CNC this is the same error i am getting.

Please help !!

**Comment by johnmichaloski** [comment]
Not sure why this is closed....  unless it was solved. 

You should check if the CNC PC has the firewall blocking Focas port 8193.  Traditionally CNC's don't have the firewall on.   Maybe local PC firewall is blocking outgoing connections.

Seeing similar issue.  So if you figured it out it would be helpful.
