### ISSUE TITLE
Fanuc Adapter - Mem Usage on 200mb and rising

### ISSUE THREAD

**Issue by diogo24m** [mtconnect/adapter#17]
I installed a Fanuc Adapter on a Raspberry (Debian) and the memory usage increased substantially in less than a day

When I run the _pmap_ command I get this:
> 636:   /home/pi/fanuc/adapter adapter.ini
> 00010000    112K r-x-- adapter
> 0003b000      4K r---- adapter
> 0003c000      4K rw--- adapter
> 00c90000 200396K rw---   [ anon ]
> 76ad2000   1248K r-x-- libc-2.28.so
> 76c0a000     64K ----- libc-2.28.so
> 76c1a000      8K r---- libc-2.28.so
> 76c1c000      4K rw--- libc-2.28.so
> 76c1d000     12K rw---   [ anon ]
> 76c20000    112K r-x-- libgcc_s.so.1
> 76c3c000     60K ----- libgcc_s.so.1
> 76c4b000      4K r---- libgcc_s.so.1
> 76c4c000      4K rw--- libgcc_s.so.1
> 76c4d000    452K r-x-- libm-2.28.so
> 76cbe000     60K ----- libm-2.28.so
> 76ccd000      4K r---- libm-2.28.so
> 76cce000      4K rw--- libm-2.28.so
> 76ccf000   1208K r-x-- libstdc++.so.6.0.25
> 76dfd000     64K ----- libstdc++.so.6.0.25
> 76e0d000     20K r---- libstdc++.so.6.0.25
> 76e12000      8K rw--- libstdc++.so.6.0.25
> 76e14000      8K rw---   [ anon ]
> 76e16000     92K r-x-- libpthread-2.28.so
> 76e2d000     60K ----- libpthread-2.28.so
> 76e3c000      4K r---- libpthread-2.28.so
> 76e3d000      4K rw--- libpthread-2.28.so
> 76e3e000      8K rw---   [ anon ]
> 76e40000    872K r-x-- libfwlib32.so.1.0.5
> 76f1a000     28K ----- libfwlib32.so.1.0.5
> 76f21000      4K r---- libfwlib32.so.1.0.5
> 76f22000      4K rw--- libfwlib32.so.1.0.5
> 76f23000     16K r-x-- libarmmem-v7l.so
> 76f27000     60K ----- libarmmem-v7l.so
> 76f36000      4K r---- libarmmem-v7l.so
> 76f37000      4K rw--- libarmmem-v7l.so
> 76f38000    128K r-x-- ld-2.28.so
> 76f5c000      8K rw---   [ anon ]
> 76f66000      8K rw---   [ anon ]
> 76f68000      4K r---- ld-2.28.so
> 76f69000      4K rw--- ld-2.28.so
> 7e8f8000    132K rw---   [ stack ]
> 7ec36000      4K r-x--   [ anon ]
> 7ec37000      4K r----   [ anon ]
> 7ec38000      4K r-x--   [ anon ]
> ffff0000      4K r-x--   [ anon ]
>  total   205320K

This is around 20% of the memory usage of raspberry (1Gb of Ram)

**Comment by bchandra2** [comment]
Were you able to solve this issue? We are attempting to do something similar. Any help or references would be appreciated.

**Comment by diogo24m** [comment]
Yes, I reinstalled the OS and the Adapter.
