### ISSUE TITLE
Modbus Adapter no facility to read swapped float values

### ISSUE THREAD

**Issue by kalpakkarnik** [mtconnect/adapter#20]
In Modbus  MtConnect adapter unable to read swapped float values .
Need one more data type along with ieee_float to read swapped float values from modbus device.

**Comment by wsobel** [comment]
Hi,

The adapter framework has not been maintained for a while. Please feel free to fix and send pull request.

Thanks,
W

**Comment by kalpakkarnik** [comment]
Hi 

I Figures out . 
In  modbus_adapter.hpp file 
under the structure ModbusFloat change the writeValue() function as below to read form swapped float register values:
  virtual void writeValues() {
    int offset = mDataItems.size();
    for (int i = 0; i < mDataItems.size(); i++) {
      uint32_t value;
      value = (static_cast<uint32_t>(mData[offset]) << 16) + mData[offset + 1];
      (static_cast<Sample*>(mDataItems[i]))->setValue(*((float*)&value));
      offset -= mSize[i];
    }
  }

Closing the thread for now ,will create and send pull request  soon 

Thanks.
