### ISSUE TITLE
Fanuc Adapter

### ISSUE THREAD

**Issue by tomsnell** [mtconnect/adapter#4]
I have been attempting to set this adapter up to a series 30i Fanuc controller with the focas2 libraries. I have followed the example on 

http://www.ellisware.com/wordpress/mtconnect-adapter-for-windows/ 

I am trying to check the adapter using 
telnet 127.0.0.1 7878
My results are from the adapter:
Connecting to Machine at 10.81.1.46 and port 8193
Result: -15

from telnet:
![telnet screen](https://cloud.githubusercontent.com/assets/8961923/4446068/543de114-47ff-11e4-9ec2-ad842b2cf972.png)

(Connection to host lost happens when I stop the adapter, I meant to not copy that part.)

From the example youtube video, it appears that it when you get -15, it isn't connecting to the machine. I setup wireshark to see if it was sending anything to the machine, I did not see any traffic coming from the adapter.

Adapter.ini:
[adapter]
port = 7878
service = MTC Focus 1

[focus]
host = 10.81.1.46
port = 8193

[macros]

[pmc]
SspeedOvr = 30
Fovr = 12

I also set the machine ip address and port. Does anyone have any ideas what I am missing?

**Comment by johnmichaloski** [comment]
Is Focas installed on your controller? If so, don’t copy in new Fwlib32.dll .  Use the existing one. You need the ethernet focas dll (hope you don’t have the hssb fwlib32.dll). If you don’t have the correct Fwlib32.dll  it won’t connect. You’re Ethernet fwlib32.dll should have a size of 861K.

8193 is the correct Ethernet IP port for focas. The IP should be to Fanuc CNC PC. If it’s an Ethernet focas library you don’t have to be on the actual controller to get it to work. You can be “anywhere”.  (Since you are reading adapter via telnet the firewall appears ok.)

**Comment by wsobel** [comment]
The error you are getting is EW_NODLL which means you do not have all the Fwlib*.dll in your path or in the same directory as the adapter.exe. 

Since you built the exe, I would assume you have the libs in which case you just need to copy Fwlib*.dll to the correct location.

Best,
Will Sobel

**Comment by tomsnell** [comment]
Focas is installed on the controller. The only thing I did there was set the Port number (TCP) to 8193, the Port number (UDP) to 0 and time interval to 0.

Looking at the focas cd that I have, there are several dll's that I can choose from. I copied the one that was fwlib32.dll, and that is 532 kb.  I see that there is a Fwlib0i.dll that is 836kb and that there is a Fwlib30i.dll, that one is 1,769 kb, which is the type of controller that I have. Should I be copying the Fwlib30i.dll into the exe folder?

**Comment by wsobel** [comment]
I would copy all the dlls over and see if it works. For the eithernet it is the E1 and the 32. They are dynamically loaded depending on the type of connection. I always just copy them all to be safe and have no surprises. If you’re running in the debugger, you can see what was dynamically loaded by looking at the output.

**Comment by tomsnell** [comment]
Looks like that took care of that hurdle. Thank you very much.

**Comment by johnmichaloski** [comment]
Try the Fwlib0i.dll that is 532K. (rename to fwlib32.dll and copy to exe directory).

Its worked for me with 30i and ethernet…
